version: '3'

tasks:
  build:
    cmds:
      - go build -v clarum.go

  test:
    deps: [unit, it]

  unit:
    cmds:
      - go test ./core/... ./http/...

  it:
    cmds:
      - go test ./itests/...
